### PR TITLE
feat:added buttons to delete table entries

### LINKED ISSUE #24: [FEAT] :sparkles: button to delete entries from tables
### Description

We need to add a button to delete entries from tables

image

image

### Anything else?

_No response_

### Are you willing to submit PR?

No

### PR DESCRIPTION
**Pull request by pavanydg**
This feature adds button to delete table entries and tax details.
closes #24

### CODE REVIEW

**Comment by pavanydg** [comment]
@aayushchugh pl review.

**Review by aayushchugh — CHANGES_REQUESTED** [review]
Logic is working correctly but UI needs some improvements.

Currently UI is not smooth because there are no transitions.

Recording 2024-11-08 at 21 58 04

Instead of showing delete on hover, we can add a new column in table named `actions` from which users can select any action that they want to perform. In this way we can add more actions in future.

eg:
image

**Comment by pavanydg** [comment]
@aayushchugh pl review

**Comment by aayushchugh** [comment]
Completed in #33

**Pull request closed without merging**
