### PR TITLE
fixed unexpected slider in billed to section.

### PR DESCRIPTION
**Pull request by userAdityaa**
<table><tbody><tr><th colspan="1" rowspan="1"><p>Before</p></th><th colspan="1" rowspan="1"><p>After</p></th></tr><tr><td colspan="1" rowspan="1"><p><div class="text-editor-image-container" data-type="image">Screenshot 2024-12-26 at 2 43 18 AM</div></p></td><td colspan="1" rowspan="1"><p><div class="text-editor-image-container" data-type="image">Screenshot 2024-12-26 at 2 43 02 AM</div></p></td></tr></tbody></table>

### Video for the fix

https://github.com/user-attachments/assets/7b1a07d9-5753-4028-877c-09668852911d

<sub><a href="https://huly.app/guest/keizerworks?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzZjNmI1YmYxNDRmNTg1YWU1MDUzNzUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Incta2VpemVyd29ya3Mta2VpemVyd29ya3MtNjc2YmIzYzQtNTg1NDc1Mzg4My00NDc3M2YifQ.gW-pIOM_E3a_VcJF6VZZOoirgPRt2ZTteU3jArb9zXc">Huly&reg;: <b>INVOI-72</b></a></sub>

### CODE REVIEW

**Comment by Sudarsh1010** [comment]
Hey @userAdityaa 
can you please share output (screenshot of address box)

**Comment by userAdityaa** [comment]
Hey @Sudarsh1010, Updated the description with the required image.

**Comment by Sudarsh1010** [comment]
Will it be scrollable? if text inside is more than 3 lines? cause you have put `overflow-hidden`
can you confirm that?

**Review by Sudarsh1010 — APPROVED** [review]

**Comment by userAdityaa** [comment]
Hey @Sudarsh1010, if you want the text-inside scrollabe then I have pushed the changes and the video is there for the change.

**Pull request merged**
