### PR TITLE
Added [FEAT] discount field in entries

### PR DESCRIPTION
**Pull request by mohdshubair313**
I have added Discount feature in UI as well as in pdf format also.
Please let me know is there anywhere I have to work more. . . .

### CODE REVIEW

**Review by aayushchugh — CHANGES_REQUESTED** [review]
@mohdshubair313 conflicts are still there. You need to update your fork with main branch

**Review by aayushchugh — CHANGES_REQUESTED** [review]
Getting these errors

image

**Comment by mohdshubair313** [comment]
ok working..

**Comment by aayushchugh** [comment]
We are changing folder structure and all so this will result in conflicts.

**Comment by mohdshubair313** [comment]
ok no problem, but we can contribute on others issue na like docker one currenly?
@aayushchugh

**Comment by aayushchugh** [comment]
@mohdshubair313 Yes, you can

**Pull request closed without merging**
